# do not install anything extra onto the image
language: generic

# use a windows image
os: windows

# only run builds on pushes to the master branch
branches:
  only:
  - master
  - develop

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change
    
# run the script to download and install Unity editor
install:
./Travis/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Travis/build.sh
